version: "3"

services:
  api:
    build:
      context: ./api/
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgresql
    command: >
      sh -c "sleep 10
             python manage.py migrate &&
             python manage.py loaddata main/data/fakedata.json &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresql
      - DB_NAME=main
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=bureauxlocaux123
      - DJANGO_SETTINGS_MODULE=api.settings
      - PYTHONUNBUFFERED=True
    volumes:
      - ./api/:/api/
  front:
    image: front
    container_name: front
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/usr/front/src
    entrypoint: ["yarn", "start"]

  postgresql:
    image: postgres:13.0
    restart: always
    volumes:
      - ./local_volumes/db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=bureauxlocaux123
      - DB_USER=postgres
    ports:
      - 5432:5432