# Generated by Django 4.2.6 on 2023-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_main_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="realty_type",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("land plot", "Land plot"),
                    ("warehouse", "Warehouse"),
                    ("retail", "Retail"),
                    ("coworking", "Coworking"),
                ],
                max_length=11,
            ),
        ),
    ]
